### ISSUE TITLE
Cicada

### ISSUE THREAD

**Issue by GreatEmerald** [GreatEmerald/UT3Vehicles#3]
Bugs related to the Cicada, reported by HellDragon.
______

UT2004  Draw  - 1.0?
UT3     Draw  - 1.3
UT3Port Draw  - 1.0 / 1.17 like the Raptor the ground collision makes it difficult to tell
NOTES:
- Priority
  - [ ] Try 1.17 or so Drawscale
  - [ ] Rotor blades are not spinning (in flight the blades are completely still)
  - [ ] Launchers on port have no collision, other than that this one has almost identical collision
  - [ ] Launchers come disconnected from the metal bar when turning
  - [ ] Rotors are in diagonal position when sitting on the ground or moving forward or backward, when hovering they are horizontal on UT3, on the port they are only diagonal when sitting on the ground
  - [ ] UT3 Cicada takes about 2-3 seconds to completely stop on it's own from full speed and in UT2004 stops almost instantly when you let go of the button (yes it's in reverse from the Raptor this time)
   - [ ] UT2004 Cicada is missing sound heard when moving at speed in UT3
   - [ ] Primary fire is not UT3 sounds
   - [ ] In UT3 Cicada also gracefully and slowly falls if you jump out in mid air, it also tucks it's turret in after it lands as well as some small squares on the front sides, UT2004 Cicada also tucks in but I think it's as soon as you get out, can't tell with how fast it falls
   - [ ] Can't tell completely for sure but it looks like in UT3 the launchers only move up and down while in UT2004 they move in every direction, might explain why they disconnect so badly in UT2004...also want to mention it looks like only the 2 launchers move and the bars they are attached to don't....launchers are also slightly in a slanted outward direction at all times in UT3
   - [ ] In UT2004 the engines are missing an animation that when hovering the engines are mostly closed and open when moving at speed in UT3

- Secondary
  - [ ] Port doesn't get knocked over by the hoverboard but still gets pushed pretty good, on UT3 it doesn't budge
  - [ ] Port has the UT2004 Raptor lights in the middle of of it, also no light is hitting the wall that I can see, I can't tell but I don't see a headlight on UT3 (stock UT2004 Cicada has lights coming from the gunner turret but here isn't supposed to be is there I don't see any indication of it from the texture)
  - [ ] Sound heard while loading missiles with alt fire is not UT3 or is very very quiet and almost unnoticeable
  - [ ] Gunner primary fire sound is not UT3
  - [ ] Shots not coming from turret barrels for Gunner position
  - [ ] Gunner primary fire seems faster than UT3
  - [ ] Gunner alt fire distance and speed feel different, seems to fall faster and less distance in UT3
  - [ ] Gunner primary has no muzzle flash in UT2004
  - [ ] Gunner primary fire in UT3 is red lasers
  - [ ] Flare is red in UT3 (is it blue with blue team, need to check that)...nope no change in any Gunner weapons colors
  - [ ] 4 thin jet trail lines are missing when moving
  - [ ] Rocket explosion sound isn't the same as UT3, UT3 sounds like a UT3 rocket
  - [ ] In UT3 the turn off or shutdown sound isn't played upon switching to gunner turret, in UT2004 it can be heard upon switching
  - [ ] Cicada collision damage is only 1-2 points of health in UT3 with any object including other vehicles, in UT2004 it takes nearly 100 points from a wall just barely bumping into it even when not moving at speed
- Tertiary
  - [ ] Launchers don't fire UT3 style missiles just the stock UT2004 Cicada missiles
  - [ ] Port engine fire isn't blue, on UT3 it has similar color to a shock core
  - [ ] Cicada gunner on UT3 doesn't have that green scope look that UT2004 port has
- Extra
  - [ ] UT3 Cicada barely tilts moving sideways even at speed, UT2004 Cicada has a lot of tilt
  - [X] UT2004 Cicada missing metallic shine

**Comment by GreatEmerald** [comment]
The headlights are a bug that you could try fixing yourself. They are controlled by the `HeadlightCoronaOffset` and `HeadlightCoronaMaterial` defaultproperties. If there are none at all in UT3, setting the `HeadlightCoronaMaterial` to `None` should make it disappear. Brake lights are controlled by `bMakeBrakeLights`.

All of the issues with the hoverboard knocking vehicles are related to impulse transfer (I'm using the Impulse tag to track this). I'm not sure if that's the hoverboard that's the culprit, or the vehicles themselves. Can you test what happens if you run into other vehicles with, say, a Manta or Scorpion in UT3 vs the mod?

The rest of the items are features not yet implemented.

**Comment by HellDragon-HK** [comment]
It is also a bug with the stock Cicada because I don't see any indication on that turret it's meant to have headlights, just for curiosity's sake.

I suspect it's the fact that in UT2004 vehicles are light and easily knocked about and in UT3 this isn't the case, which might be better left as is and for those who prefer it we can use the Heavy Vehicles mutator...assuming it actually affects the UT3 mod vehicles which I hadn't even thought to check that.

Can you confirm this as I'm not positive I'm reading it right but you want me to basically play demolition derby with various UT3 vehicles in both games right?

**Comment by GreatEmerald** [comment]
Heavy Vehicles is just for XMP, it doesn't affect anything else.

Yes, mostly it would be interesting to see whether the hoverboard pushes things as far as the Manta in both games. I'm guessing that it doesn't. And then whether the manta in UT3 pushes things as far as the UT2004 one.

**Comment by HellDragon-HK** [comment]
No no not XMP this one (from readme)

Heavy Vehicles - A mutator for UT2004 by the Fraghouse Mod Team (http://fraghouse.beyondunreal.com)
------------------

1. Installation

Here is a root structure displaying where each file should go.
.. UT2004 folder

--- System
	HeavyVehicles.u
	HeavyVehicles.int
	Heavy Vehicles.txt


Run UT2004, and from the Mutators list select Heavy Vehicles and select a map to play on (preferably with vehicles in it, y'know? ;-)).



2. Heavy Vehicles. So they're.. heavy?

Heavy Vehicles makes your vehicles heavy! Wow, that was predictable! ;-) - Nah, but seriously, if you've ever tried to play Vehicle Invasion against the Skaarj and Krall, or have ever been blasted with an Avril rocket, survived but gone spinning of the edge to a particularly nasty drop? Well, you can now weigh down your vehicles so they don't jolt about so much when they're hit.


3. Who made this? How can I contact them?

Radiosity (aka Chainsawmonkey) was the evil mastermind behind this mutator -  http://fraghouse.beyondunreal.com

Enjoy!

I have an impact tests posted for Hoverboard and Manta on their issues tab

**Comment by GreatEmerald** [comment]
Oh. That's worth a shot. Looking into the source code of it will say what variables they change to set the "weight" (probably not the actual weight, as that makes climbing cliffs and all that real hard).

Yea, now I see them, thanks.

**Comment by HellDragon-HK** [comment]
Yep no problem here to help however I can all you need do is point me in the right direction, although I don't know if I'll get more of those tests done tonight it's surprisingly exhausting smashing vehicles together

If you need or want the Heavy Vehicles mutator I've got it here https://drive.google.com/open?id=0BzR_871d9EAfblFvNzRSQ2ViOVU as I don't think Fraghouse is still around

**Comment by HellDragon-HK** [comment]
Add this to the Priority section GE - as it seems I can't
- [ ] UT3 Cicada takes about 2-3 seconds to completely stop on it's own from full speed and in UT2004 stops almost instantly when you let go of the button (yes it's in reverse from the Raptor this time)

 - [ ] UT2004 Cicada is missing sound heard when moving at speed in UT3

**Comment by HellDragon-HK** [comment]
Sorry for 3rd post in a row but I thought you would want this separate
Impact results with Cicada

Cicada Impact with Manta
-------UT3 Results--------
--Front Hit   - Medium knockback and caused Manta to spin 90 degrees, no damage taken, somewhat easily pushed (Cicada shape makes it difficult)
--Side Hit    - Medium knockback and caused Manta to spin, no damage taken, easily pushed
--Back Hit    - Medium knockback, no damage, easily pushed
--Diagnal Hit - Medium knockback and caused Manta to spin, no damage, easily pushed
------UT2004 Results------ 
--Front Hit   - Massive knockback, damaged, easily pushed like it's on ice
--Side Hit    - Medium knockback and causes Manta to spin, damaged, easily pushed like it's on ice
--Back Hit    - Medium knockback with some spin, damaged, easily pushed like it's on ice
--Diagnal Hit - Medium knockback and Manta was lifted off ground while spinning, damaged, easily pushed like it's on ice
Extra Note: Cicada takes a lot of damage in UT2004 but not in UT3

Cicada Impact with Scorpion
-------UT3 Results--------
--Front Hit   - Little or fair knockback and caused Scorpion to go vertical, no damage, cannot be pushed but very easily flipped
--Side Hit    - No knockback and was completely rolled over (it kind of rolled over in place UT3 wheeled vehicles are strange at times), no damage, cannot be pushed and surprisingly I wasn't able to flip it either
--Back Hit    - No knockback and was lifted off back wheels and turned 90 degrees, no damage, cannot be pushed but can be slightly lifted
--Diagnol Hit - Little knockback and was rolled over, no damage, can be pushed while upside down easily
------UT2004 Results------ 
--Front Hit   - Little knockback with slight turn, damaged, can be pushed
--Side Hit    - Little knockback and slightly flips, damaged, slghtest tap makes it flip
--Back Hit    - Little knockback, damaged, can be pushed
--Diagnal Hit - Little knockback slightly lifted off the ground and turned 90 degrees, damaged, can be pushed but it's really difficult due to Cicada's shape (even in UT2004 it seems)
Extra Note: In UT2004 (I've given up reported damage in UT3 at this point since I can't really see it) Scorpion took no damage but Cicada did

Cicada Impact with Hellbender
-------UT3 Results--------
--Front Hit   - Little knockback but Hellbender is thrown off the ground completely and turns 90 degrees, cannot be pushed but can almost be flipped
--Side Hit    - Little knockback and flipped on it's side, cannot be pushed but easily rolled over
--Back Hit    - Little knockback and slight turn, cannot be pushed
--Diagnol Hit - No knockback and Hellbender went slightly vertical and Cicada was deflected in a vertical direction, cannot be pushed
------UT2004 Results------ 
--Front Hit   - Fair knockback and lifted off front wheels, can be pushed
--Side Hit    - Fair knockback and flipped on it's side, cannot be pushed but can be flipped
--Back Hit    - Little knockback, can be pushed
--Diagnal Hit - Fair knockback and similar result to UT3 front hit, cannot be pushed but can be turned

Cicada Impact with Stealthbender
-------UT3 Results--------
--Front Hit   - unable to find a map that has both
--Side Hit    - 
--Back Hit    - 
--Diagnol Hit - 
------UT2004 Results------ 
--Front Hit   - pending
--Side Hit    - pending
--Back Hit    - pending
--Diagnol Hit - pending

Cicada Impact with Raptor
-------UT3 Results--------
--Front Hit   - Fair knockback with 90 degree turn and Cicada is deflected vertically, easily pushed and turned
--Side Hit    - Medium knockback with 90 degree spin, easily pushed and turned
--Back Hit    - Fair knockback with 90 degree spin, easily pushed and turned
--Diagnal Hit - Fair knockback with 180 degree spin, easily pushed and turned
------UT2004 Results------ 
--Front Hit   - Massive knockback, easily pushed and turned
--Side Hit    - Massive knockback and spins like it's on ice, easily pushed and turned
--Back Hit    - Medium knockback, easily pushed like it's on ice
--Diagnal Hit - Massive knockback and 180 degree spin, easily pushed like it's on ice

Cicada Impact with Cicada 
-------UT3 Results--------
--Front Hit   - Little knockback and other Cicada went vertical like it just got uppercut, cannot be pused but can be lifted vertical
--Side Hit    - Little knockback and other Cicada is lifted completely off ground only slightly, cannot be pushed but can be turned
--Back Hit    - Little knocback with slith turn, can kind of be pushed
--Diagnal Hit - Uppercut result again, can be turned and lifted
------UT2004 Results------ 
--Front Hit   - Fair knockback and almost 90 degree spin, easily pushed
--Side Hit    - Fair knockback and almost 90 degree spin, easily pushed
--Back Hit    - Fair knockback, can be pushed
--Diagnal Hit - Spins and rotor sections on both Cicadas collide interfering with result and this happened on every attempt, easily pushed

Cicada Impact with Hellfire SPMA
-------UT3 Results--------
--Front Hit   - No knockback but SPMA is lifted off front wheels, cannot be pushed
--Side Hit    - No knockback and SPMA came the closet to flipping on it's side I've ever seen also game felt like it wanted to crash as it got stuck for a second, can not replicate this result all I get is a slight flip attempt, cannot be pushed
--Back Hit    - No knockback and SPMA back lifted off ground, cannot be pushed
--Diagnal Hit - No knockback and Cicada is deflected, cannot be pushed
------UT2004 Results------ 
--Front Hit   - Fair knockback and SPMA was lifted off front wheels, can be pushed
--Side Hit    - Fair knockback and SPMA back was lifted off ground and turned 90 degrees, cannot be pushed but can be flipped
--Back Hit    - Medium knockback and SPMA back was lifted off ground, can be pushed and lifted off ground
--Diagnal Hit - Little knockback and SPMA flipped over, can be pushed kind of but mostly just flipped

Cicada Impact with Paladin
-------UT3 Results--------
--Front Hit   - can't find a map that has both
--Side Hit    - 
--Back Hit    - 
--Diagnal Hit - 
------UT2004 Results------ 
--Front Hit   - Little knockback, can be slowly pushed
--Side Hit    - Fair knockback and was fully rolled over, cannot be pushed because it flips at slightest tap
--Back Hit    - Fair knockback and Paladin went bottom up and turned 90 degrees, cannot be pushed becasue it flips at slightest tap
--Diagnal Hit - Fair knockback and Paladin went vertical and turned 90 degrees or more, can be slowly pushed
Extra Note: Paladin took damage in UT2004

Cicada Impact with Goliath
-------UT3 Results--------
--Front Hit   - No knockback but Goliath was slightly lifted off the ground, can be very slowly pushed
--Side Hit    - No knockback, cannot be pushed
--Back Hit    - No knockback but Goliath back was lifted off the ground, can't seem to push it
--Diagnal Hit - No knockback and Cicada is deflected vertically, can very difficultly be pushed but hard to keep Cicada from being deflected
------UT2004 Results------ 
--Front Hit   - Little knockback, can be slowly pushed and easily turned
--Side Hit    - Little knockback, can be slowly pushed
--Back Hit    - Little knockback, can be slowly pushed
--Diagnal Hit - Little or no knock back, cannot be pushed but very easily turned

Cicada Impact with Leviathan
-------UT3 Results--------
--Front Hit   - can't find a map that has both
--Side Hit    - 
--Back Hit    - 
--Diagnal Hit - 
------UT2004 Results------ 
--Front Hit   - Little knockback, can be slowly pushed
--Side Hit    - Little knockback and almost 90 degree turn, cannot be pushed
--Back Hit    - Little knockback, can be slowly pushed (wheels are spinning when pushed)
--Diagnal Hit - Little knockback with slight flip attempt, can be slowly pushed

Cicada Impact with Viper
-------UT3 Results--------
--Front Hit   - can't find a map that has both (Torlan usual Cicada in Torlan Necris is replaced by a Goliath)
--Side Hit    - 
--Back Hit    - 
--Diagnol Hit - 
------UT2004 Results------ 
--Front Hit   - pending
--Side Hit    - pending
--Back Hit    - pending
--Diagnol Hit - pending

Cicada Impact with Scavenger
-------UT3 Results--------
--Front Hit   - can't find a map that has both
--Side Hit    - 
--Back Hit    - 
--Diagnol Hit - 
------UT2004 Results------ 
--Front Hit   - pending
--Side Hit    - pending
--Back Hit    - pending
--Diagnol Hit - pending

Cicada Impact with Fury
-------UT3 Results--------
--Front Hit   - can't find a map that has both
--Side Hit    - 
--Back Hit    - 
--Diagnol Hit - 
------UT2004 Results------ 
--Front Hit   - pending
--Side Hit    - pending
--Back Hit    - pedning
--Diagnol Hit - pending

Cicada Impact with Nemesis
-------UT3 Results--------
--Front Hit   - can't find a map that has both
--Side Hit    - 
--Back Hit    - 
--Diagnol Hit - 
------UT2004 Results------ 
--Front Hit   - pending
--Side Hit    - pending
--Back Hit    - pending
--Diagnol Hit - pending

Cicada Impact with Darkwalker
-------UT3 Results--------
--Front Hit   - can't find a map that has both
--Side Hit    - 
--Back Hit    - 
--Diagnol Hit - 
------UT2004 Results------ 
--Front Hit   - pending
--Side Hit    - pending
--Back Hit    - pending
--Diagnol Hit - pending

**Comment by GreatEmerald** [comment]
OK, merged the lists. Note that I prefer striking through things that are not valid, and not striking things through if they are fixed. And no need to add checkboxes on things that are not task items.

Hm, so overall from the impact testing it feels that the issue is more the mass than the impulse. The Raptor for instance just slides as if on ice most of the times, probably because it's lacking in Karma mass. Though in the case of the hoverboard it's probably more of an impulse problem.

**Comment by HellDragon-HK** [comment]
Ok then I'll leave it to you, I did ask but didn't get a reply.   What did I list that isn't considered a task item?
It's been mostly true for air borne vehicles in general to slide around on the ground it seems.

**Comment by GreatEmerald** [comment]
See first post: "Thanks to Alex the Cicada has it's many light features and looks alive but needs some tweaking" is not a task item because you elaborate on what needs tweaking below. Same with "Front Light" etc., if there are subitems, then the parent item should not have a checkbox.

**Comment by HellDragon-HK** [comment]
Ah ok I get you, I thought making it in pieces made it easier to work with from a this is done point of view.

**Comment by HellDragon-HK** [comment]
Add this to the secondary list  
 - [ ] 4 thin jet trail lines are missing when moving

**Comment by HellDragon-HK** [comment]
This probably isn't perfect but I think it gets handling closer to what UT3 feels like, can anyone else try these and give their opinion?

    MaxRandForce=2.0
    RandForceInterval=0.95
    RollTorqueMax=60 //100
    RollTorqueStrafeFactor=130 /100
    RollTorqueTurnFactor=250 //750
    RollDamping=100.0 //30.0
    PitchTorqueFactor=50.0 //200.0
    PitchTorqueMax=20.0 //35.0
    TurnTorqueFactor=600.0
    TurnTorqueMax=220.0 //200.0
    TurnDamping=65.0 //50.0
    MaxYawRate=1.8 //1.5
    MaxRiseForce=130.0 //200
    UpDamping=0.08 //0.05
    MaxStrafeForce=45.0 //65.0
    LatDamping=0.08 //0.05
    MaxThrustForce=80.0 //80.0
    LongDamping=0.8 //0.3

Also I believe the Cicada needs to be scaled up to maybe 1.1 in Z Scale but trying to do it in the code and it will no longer move, and doing it in the animations permanently deletes collision just like the tanks.

That said the only thing I've been able to do to get it closer to UT3 is increase collision and translation which seems good but may have some side effects still unknown and needs be tested before being implemented.

https://drive.google.com/open?id=1DZCJnLy7IRMpJzHNN8loy-05YxL0lbm0

Additionally the trail effects need to be moved for the animation change and these values seem to be decent....
    TrailEffectPositions(0)=(X=-40,Y=-33,Z=90) //(X=-53,Y=-33,Z=63)
    TrailEffectPositions(1)=(X=-40,Y=33,Z=90)

**Comment by GreatEmerald** [comment]
Ugh, yea, things are getting real tough to track.
The initial idea was that "each vehicle has a few quirks that need fixing", which is why it seemed a good idea to make one issue per vehicle. But at this point you're finding so many quirks that it gets unwieldy.

In some cases, the differences affect more than just one type of vehicle. The DamageTypes, for instance, are different for a large variety of projectiles. In that case, it's better to have a new issue "Adjust DamageTypes to match UT3" or such and just remove that from all the vehicles' issues. If it is something that only affects a particular vehicle, it should remain in that vehicle's issue.

**Comment by HellDragon-HK** [comment]
Well at least Alex and I are trying to help fix what we find instead of just mentioning it, that has to help a little right?

I've been watching damage on every vehicle, most are correct from in-game testing.

**Comment by GreatEmerald** [comment]
It helps, but that's not quite what I had in mind. I meant that you should open separate issues for bugs that affect more than one vehicle (unless there are none).

Thanks for the new Cicadaissue, I'll close this one.
